name: barakah_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # -------------------------
  # Firebase Required Packages
  # -------------------------
  firebase_core: ^3.7.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.1.3

  # -------------------------
  # Local Storage
  # -------------------------
  shared_preferences: ^2.2.2

  # -------------------------
  # UI Packages
  # -------------------------
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/icons/
    - assets/fonts/
